<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="Avalonia.Headless.NUnit" />

        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Microsoft.Reactive.Testing" />
        <PackageReference Include="coverlet.collector" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Reactive.Avalonia\Reactive.Avalonia.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework" />
        <Using Include="System.Reactive" />
        <Using Include="System.Reactive.Concurrency" />
        <Using Include="System.Reactive.Disposables" />
        <Using Include="System.Reactive.Linq" />
        <Using Include="System.Reactive.Subjects" />
    </ItemGroup>

</Project>